services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data-4.4:/data/db

  rmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

#    networks:
#      - micro
#    healthcheck:
#      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')", "-u", "${MONGO_LOGIN}", "-p", "${MONGO_PASSWORD}", "--authenticationDatabase", "admin"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#
#  api:
#    build:
#      context: ./apps/eShop
#      dockerfile: Dockerfile
#    ports:
#      - "3000:3000"
#    networks:
#      - micro
#    depends_on:
#      mongo:
#        condition: service_healthy
#
#networks:
#  micro:
#    driver: bridge
